### PR TITLE
Update section on task runners

### PR DESCRIPTION
**Pull request by ryami333**
Gulp is out, npm scripts are in.

### CODE REVIEW

**Comment by holloway** [comment]
I generally agree, and regular scripts are definitely more minimal (fewer deps) and easier to maintain.

Could you add something to the `CHANGELOG.md` describing how to migrate?

I don't care much about `vinyl` and streaming data pipelines (like SAX it's benefits are overblown, or at least a niche use-case, considering that most stages of the pipeline need the full data) but the _parallel_ gulp stuff is a pattern that I appreciate.

So I presume that to replicate that parallel functionality we'd do `promise.all( glob('*.jpg').map(somePath =>  promise(...).then.then.then)` ... if so perhaps a basic code example might be useful.

**Comment by ryami333** [comment]
@holloway I've raised the issue about parallel tasks, so I think we can merge this now.

**Comment by holloway** [comment]
@ryami333 thanks, i'm happy to merge this

**Comment by holloway** [comment]
good stuff @ryami333 :)

**Pull request merged**
