### PR TITLE
Update third-party tools section

### PR DESCRIPTION
**Pull request by ryami333**
Remove redundant line about dependencies being listed in package.json, add some specific examples of preferred third-party packages.

### CODE REVIEW

**Comment by holloway** [comment]
I'm not sure if the questionnaire is where we should be recommending/discouraging particular packages. Let's talk more in person though

**Comment by ryami333** [comment]
Fair enough, happy to remove this section - "check the package.json to see dependencies" was really the only thing I badly wanted to address. It's redundant, or rather it requisite knowledge.

**Comment by ryami333** [comment]
@holloway happy to merge this now?

**Comment by holloway** [comment]
Yep -- definitely an improvement and definitely not a regression :)

merging... and ta!

**Pull request merged**
